### ISSUE TITLE
real streaming

### ISSUE THREAD

**Issue by hackergrrl** [noffle/resync-srt#1]
Use something like [srt-stream-parser](https://github.com/steffenmllr/srt-stream-parser) for reading, and hack something together for writing SRT.

**Comment by benadamstyles** [comment]
Is this why I get the following error?

```
/Users/ben/.nvm/versions/node/v4.0.0/lib/node_modules/resync-srt/index.js:19
    this.push(sub.stringfy().trim())
                  ^

TypeError: sub.stringfy is not a function
    at DestroyableTransform.flush [as _flush] (/Users/ben/.nvm/versions/node/v4.0.0/lib/node_modules/resync-srt/index.js:19:19)
    at DestroyableTransform.<anonymous> (/Users/ben/.nvm/versions/node/v4.0.0/lib/node_modules/resync-srt/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:123:12)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at prefinish (/Users/ben/.nvm/versions/node/v4.0.0/lib/node_modules/resync-srt/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:501:12)
    at finishMaybe (/Users/ben/.nvm/versions/node/v4.0.0/lib/node_modules/resync-srt/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:509:7)
    at endWritable (/Users/ben/.nvm/versions/node/v4.0.0/lib/node_modules/resync-srt/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:521:3)
    at DestroyableTransform.Writable.end (/Users/ben/.nvm/versions/node/v4.0.0/lib/node_modules/resync-srt/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:486:5)
    at ReadStream.onend (_stream_readable.js:490:10)
```

**Comment by hackergrrl** [comment]
Thanks for the report. This wasn't due to lack of streaming -- `stringfy` got renamed to `stringify` in an upstream dependency. Fixed in `3.1.0`!

**Comment by benadamstyles** [comment]
Ah yes! Thanks v much.

**Comment by benadamstyles** [comment]
You can close this

**Comment by hackergrrl** [comment]
The issue is for tracking streaming support, so I'll leave it open until then. :)

**Comment by benadamstyles** [comment]
Ah yes, sorry, doing too many things at once!
